# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  ARTIFACTS_ENV_ACCESS_URI: $(AZURE_ARTIFACTS_ENV_ACCESS_URI)
  ARTIFACTS_ENV_ACCESS_USERNAME: $(AZURE_ARTIFACTS_ENV_ACCESS_USERNAME)
  ARTIFACTS_ENV_ACCESS_TOKEN: $(AZURE_ARTIFACTS_ENV_ACCESS_TOKEN)

steps:
- task: Gradle@2
  displayName: Publish
  inputs:
    tasks: 'publish'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false
    gradleWrapperFile: $(System.DefaultWorkingDirectory)/gradlew
    jdkVersionOption: 1.11
    workingDirectory: $(System.DefaultWorkingDirectory)
    publishJUnitResults: false
