trigger:
- none

parameters:
- name: version
  displayName: Semantic Versioning
  type: string
  default: PATCH
  values:
  - PATCH
  - MINOR
  - MAJOR

pool:
  vmImage: ubuntu-latest

jobs:
- ${{ if eq(parameters.version, 'PATCH') }}:
  - job: "increase_patch"
    displayName: "Subindo versão tipo PATCH"
    steps:
    - script: echo "I did a PATCH"
- ${{ if eq(parameters.version, 'MINOR') }}:
  - job: "increase_minor"
    displayName: "Subindo versão tipo MINOR"
    steps:
    - script: echo "I did a MINOR"
- ${{ if eq(parameters.version, 'MAJOR') }}:
  - job: "increase_major"
    displayName: "Subindo versão tipo MAJOR"
    steps:
    - script: echo "I did a MAJOR"
- job: "Publishing_artifact"
  displayName: "Publicando artefato"
  steps:
  - task: Gradle@2
    inputs:
      gradleWrapperFile: 'gradlew'
      tasks: 'build publish'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      sonarQubeRunAnalysis: false
      spotBugsAnalysis: false