trigger:
- none

parameters:
- name: version
  displayName: Semantic Versioning
  type: string
  default: PATCH
  values:
  - PATCH
  - MINOR
  - MAJOR

pool:
  vmImage: ubuntu-latest

steps:
- ${{ if eq(parameters.version, 'PATCH') }}:
  - script: echo "I did a PATCH"
- ${{ if eq(parameters.version, 'MINOR') }}:
  - script: echo "I did a MINOR"
- ${{ if eq(parameters.version, 'MAJOR') }}:
  - script: echo "I did a MAJOR"
- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build publish'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false
