trigger:
- none

parameters:
- name: version
  displayName: Semantic Versioning
  type: string
  default: PATCH
  values:
  - PATCH
  - MINOR
  - MAJOR

pool:
  vmImage: ubuntu-latest

steps:
- script: echo I did a PATCH
  condition: eq('${{ parameters.version }}' , 'PATCH')
- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build publish'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false
