# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

parameters:
- name: version
  displayName: Semantic Versioning
  type: string
  default: PATCH
  values:
  - PATCH
  - MINOR
  - MAJOR

jobs:
  - job: B
    steps:
    - script: echo I did a PATCH
    condition: eq(parameters.version, 'PATCH')

pool:
  vmImage: ubuntu-latest

steps:
- task: Gradle@2
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'build publish'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false
