# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadSecureFile@1
  name: settings
  displayName: 'Download settings.xml'
  inputs:
    secureFile: 'settings.xml'

- script: |
    echo Installing $(settings.secureFilePath) to the /.m2...
    sudo chown root:root $(settings.secureFilePath)
    sudo chmod a+r $(settings.secureFilePath)
    sudo cp $(settings.secureFilePath) $HOME/.m2

- task: Gradle@2
  displayName: Publish
  inputs:
    tasks: 'publish'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false
    gradleWrapperFile: $(System.DefaultWorkingDirectory)/gradlew
    jdkVersionOption: 1.11
    workingDirectory: $(System.DefaultWorkingDirectory)
    publishJUnitResults: false
